### PR TITLE
Added pageSize config parameter for queryDocs.

### PR DESCRIPTION
**Pull request by jpkrebs**

### CODE REVIEW

**Comment by wattsferry** [comment]
Looking at MC-20, it doesn't appear that this covers offset and limit at first glance, but let me know if I'm wrong.

**Comment by wattsferry** [comment]
static long | DEFAULT_PAGE_LENGTHThe default maximum number of documents in a page of search results.
-- | --
static long | STARTThe offset of the first result in the default page.

**Comment by wattsferry** [comment]
Actually, more specifically, you can use QueryManager's fields:

|{{static long}}|{{[DEFAULT_PAGE_LENGTH|https://project.marklogic.com/com/marklogic/client/query/QueryManager.html#DEFAULT_PAGE_LENGTH]}}
The default maximum number of documents in a page of search results.|
|{{static long}}|{{[START|https://project.marklogic.com/com/marklogic/client/query/QueryManager.html#START]}}
The offset of the first result in the default page.|

**Comment by jpkrebs** [comment]
@wattsferry  Hold off on accepting this PR until I have had a chance to implement max pages functionality.

**Comment by jpkrebs** [comment]
@wattsferry I went with maxResults, rather than maxPages.  Turns out this was much more straightforward to implement, and requires less math on the user's part.  We could in theory add maxPages as well in the future.  Anyway, this PR should now be ready for acceptance.

**Comment by wattsferry** [comment]
Hi Jonathan, I think we're close, I've confirmed the functionality.  There's only one glaring issue, and that's if the user doesn't specify a Maximum Number of Results, it doesn't actually return the unlimited set.  It's still returning zero results. As soon as I put in a value > 0, it works.

**Pull request merged**
